---
all:
  children:
    budget_api:
      hosts:
        piggy_pulse_prod:
          ansible_host: 10.66.0.1
          ansible_user: deploy
          ansible_port: 22
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
