---
all:
  children:
    budget_api:
      hosts:
        piggy_pulse_prod:
          ansible_host: 46.225.124.136
          ansible_user: root
          ansible_port: 22
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
