---
- name: Harden and deploy PiggyPulse
  hosts: piggy_pulse_api
  become: true
  gather_facts: true

  roles:
    - role: common
      tags: ["common"]

    - role: wireguard
      tags: ["wireguard"]

    - role: security
      tags: ["security"]

    - role: docker
      tags: ["docker"]

    - role: app
      tags: ["app"]
